#!/bin/bash

function scriptDir
{
        SOURCE="${BASH_SOURCE[0]}"

        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
		# if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
        echo -e "View remote rtsp stream"
        echo -e "Arguments:"
        echo -e "-ip addr"
        echo -e "-user user"
        echo -e "-pass password"
        echo -e "[ -path /stream.dsp ]"
        echo -e "fg: view -ip 192.168.140.229 -user admin -pass password1"
}


ip=`valueArg "ip"` || errorOut "IP address missing" 
user=`valueArg "user"`
pass=`valueArg "pass"`
path=`valueArg "path"`
dst=`valueArg "img"` || errorOut "destination image"

[[ -n "$user" && -n "$pass" ]] && prefix="$user:$pass@"

ffmpeg -i "rtsp://$prefix$ip"  -vframes 1 -update 1 $dst
