#!/bin/bash

function scriptDir
{    
        SOURCE="${BASH_SOURCE[0]}"
    
        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
        echo -e "Generate random VALID mac address"
}

sdir=`scriptDir`

source "${sdir}/../include/utils"
initArg $@
hasArg h && { scriptHelp; errorOut; }

path=`getVariable "${sdir}/conf" "NETCTL_PATH" "path"`

#echo -e "${path}"

profiles=( $( find "${path}" -maxdepth 1 -type f ) )

for profile in ${profiles[@]}
do 
	tmp=$( basename "${profile}" )
	${sdir}/profileInfo "-name ${tmp}"
done
