#!/bin/bash

function scriptDir
{    
        SOURCE="${BASH_SOURCE[0]}"
    
        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located      
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
        echo -e "Deploy mail server gateway"
}

#if [ $# != 1  ]; then
#        echo -e "Invalid number of arguments should be:$0 vhost"
#        errorOut
#fi

sdir=`scriptDir`
source "${sdir}/../include/utils"
initArg "$@"

mailDBEngine=`getVariable "${sdir}/conf" "MAIL_DB_ENGINE" "alpha"` || errorOut "Failed to get database type"
maildb=`getVariable "${sdir}/conf" "MAIL_DB" "mixed"` || errorOut "Failed to get mail database name"
maildbUser=`getVariable "${sdir}/conf" "MAIL_DB_USER" "mixed"` || errorOut "Failed to get mail database user"
maildbPass=`getVariable "${sdir}/conf" "MAIL_DB_PASS" "mixed"` || errorOut "Failed to get mail database password"
maildbHost=`getVariable "${sdir}/conf" "MAIL_DB_HOST" "ip"` || errorOut "Failed to get database ip address"
maildbPort=`getVariable "${sdir}/conf" "MAIL_DB_PORT" "port"` || errorOut "Failed to get database port"
postfixLoc=`getVariable "${sdir}/conf" "POSTFIX_DIR" "path"` || errorOut "Failed to get postfix configuration location"
dovecotLoc=`getVariable "${sdir}/conf" "DOVECOT_DIR" "path"` || errorOut "Failed to get dovecot configuration location"
authMechanism=`getVariable "${sdir}/conf" "AUTH_MECHANISM" "custom" "[A-Z0-9-]+"` || errorOut "Failed to get password scheme"
user=`getVariable "${sdir}/conf" "MAIL_USER" "user"` || errorOut "Failed to get owner user"
group=`getVariable "${sdir}/conf" "MAIL_GROUP" "group"` || errorOut "Failed to get owner group"
userid=`getVariable "${sdir}/conf" "MAIL_USER_ID" "integer"` || errorOut "Failed to get owner user id"
groupid=`getVariable "${sdir}/conf" "MAIL_GROUP_ID" "integer"` || errorOut "Failed to get group owner id"

#echo "$mailDBEngine"
#echo "$maildb"
#echo "$maildbUser"
#echo "$maildbPass"
#echo "$maildbHost"
#echo "$maildbPort"
#echo "$postfixLoc"

copy "${sdir}/main.cf" "${postfixLoc}/main.cf" || errorOut "Failed to copy main.cf"
setVariable "${postfixLoc}/main.cf" "MAIL_DB_ENGINE" "${mailDBEngine}" || errorOut "Failed to set mail database engine in main.cf"
setVariable "${postfixLoc}/main.cf" "POSTFIX_DIR" "${postfixLoc}" || errorOut "Failed to set postfix location in main.cf"

copy "${sdir}/relay_domains_maps.cf" "${postfixLoc}/relay_domains_maps.cf" || errorOut "Failed to copy relay_domains_maps.cf"
setVariable "${postfixLoc}/relay_domains_maps.cf" "MAIL_DB_USER" "${maildbUser}"
setVariable "${postfixLoc}/relay_domains_maps.cf" "MAIL_DB_PASS" "${maildbPass}"
setVariable "${postfixLoc}/relay_domains_maps.cf" "MAIL_DB_HOST" "${maildbHost}"
setVariable "${postfixLoc}/relay_domains_maps.cf" "MAIL_DB_PORT" "${maildbPort}"
setVariable "${postfixLoc}/relay_domains_maps.cf" "MAIL_DB" "${maildb}"

copy "${sdir}/relay_recipients_maps.cf" "${postfixLoc}/relay_recipients_maps.cf" || errorOut "Failed to copy relay_recipients_maps.cf"
setVariable "${postfixLoc}/relay_recipients_maps.cf" "MAIL_DB_USER" "${maildbUser}"
setVariable "${postfixLoc}/relay_recipients_maps.cf" "MAIL_DB_PASS" "${maildbPass}"
setVariable "${postfixLoc}/relay_recipients_maps.cf" "MAIL_DB_HOST" "${maildbHost}"
setVariable "${postfixLoc}/relay_recipients_maps.cf" "MAIL_DB_PORT" "${maildbPort}"
setVariable "${postfixLoc}/relay_recipients_maps.cf" "MAIL_DB" "${maildb}"

copy "${sdir}/relay_transports_maps.cf" "${postfixLoc}/relay_transports_maps.cf" || errorOut "Failed to copy relay_transports_maps.cf"
setVariable "${postfixLoc}/relay_transports_maps.cf" "MAIL_DB_USER" "${maildbUser}"
setVariable "${postfixLoc}/relay_transports_maps.cf" "MAIL_DB_PASS" "${maildbPass}"
setVariable "${postfixLoc}/relay_transports_maps.cf" "MAIL_DB_HOST" "${maildbHost}"
setVariable "${postfixLoc}/relay_transports_maps.cf" "MAIL_DB_PORT" "${maildbPort}"
setVariable "${postfixLoc}/relay_transports_maps.cf" "MAIL_DB" "${maildb}"

copy "${sdir}/virtual_sender_login_maps.cf" "${postfixLoc}/virtual_sender_login_maps.cf" || errorOut "Failed to copy relay_domains_maps.cf"
setVariable "${postfixLoc}/virtual_sender_login_maps.cf" "MAIL_DB_USER" "${maildbUser}"
setVariable "${postfixLoc}/virtual_sender_login_maps.cf" "MAIL_DB_PASS" "${maildbPass}"
setVariable "${postfixLoc}/virtual_sender_login_maps.cf" "MAIL_DB_HOST" "${maildbHost}"
setVariable "${postfixLoc}/virtual_sender_login_maps.cf" "MAIL_DB_PORT" "${maildbPort}"
setVariable "${postfixLoc}/virtual_sender_login_maps.cf" "MAIL_DB" "${maildb}"

copy "${sdir}/dovecot.conf" "${dovecotLoc}/dovecot.conf" || errorOut "Failed to copy dovecot.conf"
setVariable "${dovecotLoc}/dovecot.conf" "AUTH_MECHANISM" "${authMechanism}" || errorOut "Failed to set authentication mechanism is dovecot-sql.conf"

copy "${sdir}/dovecot-sql.conf" "${dovecotLoc}/dovecot-sql.conf" || errorOut "Failed to copy dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_DB_PORT" "${maildbPort}" || errorOut "Failed to set port in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_DB_ENGINE" "${mailDBEngine}" || errorOut "Failed to set mail database type in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_DB_HOST" "${maildbHost}" || errorOut "Failed to set mail database host in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_DB" "${maildb}" || errorOut "Failed to set mail database name in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_DB_USER" "${maildbUser}" || errorOut "Failed to set mail database user name in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_DB_PASSWORD" "${maildbPass}" || errorOut "Failed to set mail database password in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_HOME" "${mailHome}" || errorOut "Failed to set mail home directory in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_USER_ID" "${userid}" || errorOut "Failed to set virtual mail user id in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "MAIL_GROUP_ID" "${groupid}" || errorOut "Failed to set virtual group id in dovecot-sql.conf"
setVariable "${dovecotLoc}/dovecot-sql.conf" "AUTH_MECHANISM" "${authMechanism}" || errorOut "Failed to set authentication mechanism is dovecot-sql.conf"

copy "${sdir}/master.cf" "${postfixLoc}/master.cf"
