#!/bin/bash

function scriptDir
{
	SOURCE="${BASH_SOURCE[0]}"

	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
		DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
		SOURCE="$(readlink "$SOURCE")"
		[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done

	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	echo $DIR
}

function scriptHelp
{
	echo -e "Delete lighttpd listen interface specified by -iface"
	echo -e "Arguments:"
	echo -e "-iface interface"
	echo -e "fg: delinterface -iface enp3s1"
}

sdir=`scriptDir`
source "${sdir}/../include/utils"
initArg $@
sizeArg || { scriptHelp; errorOut; }
hasArg h && { scriptHelp; errorOut; }

ifaceName=`valueArg "iface"`

owner=`getVariable "${sdir}/conf" "USER" "custom" "[A-Za-z]+[A-Za-z0-9]+"` || errorOut "Failed to get lighttpd owner user"
group=`getVariable "${sdir}/conf" "GROUP" "custom" "[A-Za-z]+[A-Za-z0-9]+"` || errorOut "Failed to get lighttpd owner group"
lightConf=`getVariable "${sdir}/conf" "LIGHTTPD_CONF" "path"` || errorOut "Failed to get lighttpd configuration directory"

ifaces=`ls -lah "${lightConf}/listen.d" | awk '{ if(NR!=1) { print } }' | grep -Ev -e "(\.$)|(\.\.$)" | awk 'BEGIN { FS=" " } ; { print $9  }' | sed "s#\.conf##g"`
ifaces=($ifaces)

if [ -z "$( echo "${ifaces[@]}" | grep -E -e "${ifaceName}" )" ]; then
	errorOut "No such interface: ${ifaceName}"
fi

checkRead "${lightConf}/listen.d/${ifaceName}.conf" && rm -f "${lightConf}/listen.d/${ifaceName}.conf"

if [ ! -z "$( cat "${lightConf}/lighttpd.conf" | grep -E -e "(include)[[:blank:]]+\"listen\.d/${ifaceName}\.conf\"" )" ]; then
	ifaceNameEsc=`regexpEscape "${ifaceName}"`
	removeFromFile "${lightConf}/lighttpd.conf" "(include)[[:blank:]]+\"listen\.d/${ifaceNameEsc}\.conf\""
	touchFile "${lightConf}/lighttpd.conf" "${owner}" "${group}"
fi
