#!/bin/bash

function scriptDir
{
        SOURCE="${BASH_SOURCE[0]}"

        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
	echo -e "Delete virtual host from lighttpd specified by -vhost"
	echo -e "Arguments:"
	echo -e "-vhost host"
	echo -e "fg: delete -vhost somehost.exampledomain.com"
}

sdir=`scriptDir`
source "${sdir}/../include/utils"
initArg $@
sizeArg || { scriptHelp; errorOut; }
hasArg h && { scriptHelp; errorOut; }
vhost=`valueArg "vhost"`

home=`getVariable "${sdir}/conf" "HOME" "path" || errorOut`
lightConf=`getVariable "${sdir}/conf" "LIGHTTPD_CONF" "path" || errorOut`

checkDir "${home}" &> /dev/null || errorOut "lighttpd home directory does not exist"
checkDir "${lightConf}" &> /dev/null || errorOut "lighttpd configuration directory does not exist"

if [ -d "${home}/${vhost}" ]; then
	if [ "${home}/${vhost}" != "/" ]; then
		rm -rf "${home}/${vhost}" &> /dev/null
	fi
fi

if [ -f "${lightConf}/host.d/${vhost}.conf" ]; then
	if [ "${lightConf}/host.d/${vhost}.conf" != "/" ]; then
		rm -rf "${lightConf}/host.d/${vhost}.conf" &> /dev/null
	fi
fi

vhostIfs=`${sdir}/vhostinfo "-vhost ${vhost}" | grep -E -e "Interfaces:" | grep -Eo -e ":.+" | grep -Eo -e "([A-Za-z0-9]+[ ]*)+"`
vhostEsc=`regexpEscape "${vhost}"`

for Iface in $vhostIfs
do
	removeFromFile "${lightConf}/listen.d/${Iface}.conf" "(include)[[:blank:]]+(\"host\.d/${vhostEsc}\.conf\")"
done
