#!/bin/bash

function scriptDir
{
        SOURCE="${BASH_SOURCE[0]}"

        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
	echo -e "Display information about lighttpd listen interface specified by -iface"
	echo -e "Arguments:"
	echo -e "-iface interface"
	echo -e "fg: interfaceinfo enp5s0"
}

sdir=`scriptDir`
source "${sdir}/../include/utils"
initArg $@
sizeArg || { scriptHelp; errorOut; }
hasArg h && { scriptHelp; errorOut; }
iface=`valueArg "iface"`


lightConf=`getVariable "${sdir}/conf" "LIGHTTPD_CONF" "path" || errorOut`

checkRead "${lightConf}/listen.d/${iface}.conf" &> /dev/null || errorOut "Specified interface:${iface} does not exist"

ifConf="${iface}.conf"

tmp=`cat "${lightConf}/listen.d/${ifConf}" | grep -E -e "$SERVER\[\"socket\"\]" | awk 'BEGIN { FS=" " } ; { print $3 }' | grep -Eo -e "[0-9\.:]+"`
ifIP=`echo "${tmp}" | awk 'BEGIN { FS=":" } ; { print $1}'`
ifPort=`echo "${tmp}" | awk 'BEGIN { FS=":" } ; { print $2 }'`
echo -e "Interface:${ifConf}" | sed "s#\.conf##g"
echo -e "\tIP:${ifIP}"
echo -e "\tPort:${ifPort}"
esc=`regexpEscape "$ifConf"`
if [ "$( cat ${lightConf}/lighttpd.conf | grep -E -e "(include)[[:blank:]]+\"listen\.d/${esc}\"" )" ]; then
	echo -e "\tlighttpd.conf: OK"
else
	echo -e "\tlighttpd.conf: MISSING"
fi
