#!/bin/bash

function scriptDir
{
        SOURCE="${BASH_SOURCE[0]}"

        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

sdir=`scriptDir`
source "${sdir}/../include/utils"

checkInstall conntrack-tools
checkInstall pbzip2
checkInstall iptraf-ng
checkInstall iotop
checkInstall iputils
checkInstall bridge-utils
checkInstall smartmontools
checkInstall bridge-utils
checkInstall tcpdump
checkInstall net-tools
checkInstall sed
