#!/bin/bash

function scriptDir
{       
        SOURCE="${BASH_SOURCE[0]}"
        
        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
        echo -e "Restore database from dump in specified postgres instance"
        echo -e "Arguments:"
        echo -e "-host database host"
        echo -e "-port database port"
        echo -e "-dbname database name"
        echo -e "-dbuser database user"
	echo -e "-input input file"
}

sdir=`scriptDir`
source "${sdir}/../include/utils"

initArg "$@"
hasArg "h" && { scriptHelp; errorOut; }

host=$( valueArg "host" ) || { scriptHelp; errorOut; }
port=$( valueArg "port" ) || { scriptHelp; errorOut; }
dbname=$( valueArg "dbname" ) || { scriptHelp; errorOut; }
dbuser=$( valueArg "dbuser" ) || { scripthelp; errorOut; }
in=$( valueArg "input" ) || { scriptHelp; errorOut; }

pg_restore "-h" "${host}" "-p" "${port}" "-d" "${dbname}" "-U" "${dbuser}" "${in}" || errorOut
