#!/bin/bash

function scriptDir
{       
        SOURCE="${BASH_SOURCE[0]}"
        
        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
        echo -e "Display info about VPS"
        echo -e "Arguments:"
	echo -e "-name name of vps serwer"
}

sdir=`scriptDir`

source "${sdir}/../include/utils"
initArg $@
sizeArg || { scriptHelp; errorOut; }
hasArg "h" && { scriptHelp; errorOut; }
name=`valueArg "name"` || { scriptHelp; errorOut; }
path=`getVariable "${sdir}/conf" "VPS_PATH" "path"` || { scriptHelp; errorOut; }

checkDir "${path}/vm/${name}" &> /dev/null || errorOut
