#!/bin/bash

function scriptDir
{
        SOURCE="${BASH_SOURCE[0]}"

        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
	echo -e "Process OUI list supllied by http://standards-oui.ieee.org/oui.txt to more friendly format"
	echo -e "Arguments:"
	echo -e "-input input oui file"
	echo -e "-output file to write friendly ouis"
}

sdir=`scriptDir`

source "${sdir}/../include/utils"
initArg $@
sizeArg || { scriptHelp; errorOut; }
hasArg h && { scriptHelp; errorOut; }

input=`valueArg input` || { scriptHelp; errorOut; }
output=`valueArg output` || { scriptHelp; errorOut; }

cat "${input}" | grep -Eo -e "^([0-9A-Z]{2}(-)){2}([0-9A-Z]{2})" | awk 'BEGIN { FS="-" } ; { print $1":"$2":"$3}' > "${output}"
