#!/bin/bash

function scriptDir
{       
        SOURCE="${BASH_SOURCE[0]}"
        
        while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
                DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        echo $DIR
}

function scriptHelp
{
	echo -e "Generate random VALID mac address"
}

sdir=`scriptDir`

source "${sdir}/../include/utils"
initArg "$@"
#sizeArg || { scriptHelp; errorOut; }
hasArg h && { scriptHelp; errorOut; }

begin=$( fileNthLine "${sdir}/oui.txt" $(randomInt32 `fileLines "${sdir}/oui.txt"`) )

for i in {0..2}
do
	tmp=$( printf "%X" $( randomInt32 256 ) )
	if [ ${#tmp} == 1 ]; then
		tmp="0${tmp}"
	fi
	end="${end}:${tmp}"
done

echo -e "${begin}${end}"
