#!/bin/bash

file="/etc/locale.gen"

if [ ! -w $file ]; then
	echo -e "Cant write to $file"
	exit 1
fi

echo "en_GB.UTF-8 UTF-8" > $file
echo "en_GB ISO-8859-1" >> $file
echo "en_US.UTF-8 UTF-8" >> $file  
echo "en_US ISO-8859-1" >> $file
echo "pl_PL.UTF-8 UTF-8" >> $file
echo "pl_PL ISO-8859-2" >> $file

locale-gen 
